apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: deployment-container
          image: your-image-name
          ports:
            - containerPort: 3000